# Generated by Django 5.2.6 on 2025-09-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
