# Generated by Django 5.2.6 on 2025-10-06 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_id'),
        ('wallet', '0008_alter_wallet_currency_alter_wallet_expired_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='wallet.currency'),
        ),
    ]
