# Generated by Django 5.2.6 on 2025-10-06 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0008_alter_card_currency'),
        ('wallet', '0008_alter_wallet_currency_alter_wallet_expired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='currency',
            field=models.ForeignKey(default='091f557f-53bd-4a38-af7d-7f7fe71a86e3', on_delete=django.db.models.deletion.PROTECT, to='wallet.currency'),
        ),
    ]
