# Generated by Django 5.2.6 on 2025-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0009_alter_card_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
