# Generated by Django 5.2.6 on 2025-09-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_number',
            field=models.PositiveIntegerField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
