# Generated by Django 5.2.6 on 2025-09-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_wallet_wallet_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
