# Generated by Django 5.2.6 on 2025-09-28 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0004_wallet_expired_date_alter_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(default='UZS', on_delete=django.db.models.deletion.PROTECT, to='wallet.currency'),
        ),
    ]
