# Generated by Django 5.2.6 on 2025-10-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_wallet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(db_index=True, default='UZS', max_length=200),
        ),
    ]
