# Generated by Django 5.2.6 on 2025-10-01 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_alter_currency_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wallet.currency'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='expired_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_number',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
