# Generated by Django 5.2.6 on 2025-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_alter_wallet_currency_alter_wallet_expired_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='wallet_number',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
